spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zcblog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root


logging:
  level:
    root: info
    com.lrm: debug
  file: log/blog-dev.log

server:
  port: 8080

